# Site settings
title: CandY Blog
SEOTitle: 图格曼斯的博客 | CandY Blog
header-img: img/post-bg-desk.jpg
email: a331398868@gmail.com
description: "Every failure is leading towards success."
keyword: "CNj, CNJ Blog, 图格曼斯的博客, cainengjain, 蔡能健, WEB, PYTHON"
url: "https://jimmaster.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/JimMaster/JimMaster.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-CNj-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     cai-neng-jian
github_username:    JimMaster
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
disqus_username: cainengjian

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: de19ebe3cad04df2e1af                            #生成的clientID
  clientSecret: e7150bf495df340c4d70424137147f359e02d658    #生成的clientSecret
  repo: JimMaster.github.io    #仓库名称
  owner: cainengjian    #github用户名
  admin: [cainengjian]
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: cee724dbd96d2a0044a3ef008d524b7e

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    # {
    #     title: "WY",
    #     href: "https://www.zhihu.com/people/cai-neng-jian/activities"
    # },{
    #     title: "简书·BY",
    #     href: "http://www.jianshu.com/u/e71990ada2fd"
    # },{
    #     title: "Apple",
    #     href: "https://apple.com"
    # },{
    #     title: "Apple Developer",
    #     href: "https://developer.apple.com/"
    # }
]
